[package]
name = "photobooth-hub"
version = "0.1.0"
authors = ["Malcolm Vigren"]
edition = "2024"

[dependencies]
gphoto2 = "3.4.1"
image = "0.25.6"
macroquad = "0.4.14"

[profile.release]
lto="fat"

